config/routes.rb
PathsCc::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  namespace :backend do
    resources :monuments
    resources :users
    resources :sessions, only: :create

    root to: 'dashboard#show'
    get 'login' => 'sessions#new', :as => :login
    get 'logout' => 'sessions#destroy', :as => :logout
  end

  root to: 'homepage#show'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.is_a? Admin
        can :manage, :all
        can :manage, :monuments
        can :manage, :monument_translations
        can :access, :ckeditor
      else
        can :read, :all
      end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Dragonfly

  ckeditor_file_accessor :data
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  validates_property :format, :of => :data, :in => attachment_file_types unless attachment_file_types.empty?

  def url_thumb
    Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  validates_property :format, :of => :data, :in => image_file_types unless image_file_types.empty?
  validates_property :image?, :of => :data, :as => true, :message => :invalid

  def url_content
    data.thumb("800x800>").url
  end

  def url_thumb
    data.thumb("118x100#").url(url_thumb_options)
  end
end

app/models/concerns/translatable.rb
module Translatable
  extend ActiveSupport::Concern
  included do
    has_many :translations
    attr_accessible :translations_attributes
    accepts_nested_attributes_for :translations, allow_destroy: true
  end
end

app/models/monument.rb
class Monument < ActiveRecord::Base

  # Translations
  translates :name, :title, :description, versioning: true

  # Associations
  belongs_to :user

  class Translation
    attr_accessible :locale
  end

  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Sorcery
  authenticates_with_sorcery!
  
  # Validations
  validates :email,                   presence: true, uniqueness: true
  validates :username,                presence: true, uniqueness: true
  validates :password,                presence: true, confirmation: true, length: { minimum: 3}
  validates :password_confirmation,   presence: true
  
  # Associations
  has_many :monuments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < ActionController::Base
  layout "backend"
  protect_from_forgery with: :exception
  before_filter :require_login, except: :not_authenticated
  helper_method :current_users_list
  inherit_resources
  respond_to :html, :json

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  protected
    def not_authenticated
      redirect_to backend_login_path, :alert => "Please login first."
    end

    def current_users_list
      current_users.map {|u| u.email}.join(", ")
    end
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::ApplicationController
  def show
  end
end

app/controllers/backend/monuments_controller.rb
class Backend::MonumentsController < Backend::ApplicationController
  respond_to :html, :json
  load_and_authorize_resource

  public
  def permitted_params
    params.permit(monument: [:user_id, :name, :title, :description, :locale])
  end
end

app/controllers/backend/sessions_controller.rb
class Backend::SessionsController < Backend::ApplicationController
  before_action :login_user,    only: :create
  before_action :require_login, only: :destroy
  layout 'sessions'
  respond_to :html, :js, :xml

  def new
  end

  def create
    if @user
      redirect_back_or_to backend_root_url, notice: 'Logged in!'
    else
      redirect_to backend_login_url, alert: 'Email or password was invalid.'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Successfully logged out.'
  end

  private
    def login_user
      @user = login(params[:session][:email], params[:session][:password])
    end

    def session_params
      params.require(:user).permit(:email, :password, :passowrd_confirmation)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/backend/dashboard/show.html.haml
%header.content-header
  %h1.light.no-margin Dashboard

%section.bordered
  .container-fluid
    .metro-area
      %ul.metro-shortcut.clearfix.unstyled
        %li.item.wide
          .box.bg-color.green
            %i.icon-camera
            %span.count 10
            %h4.header.light New Messages
        -# %li.item
        -#   .box.bg-color.red
        -#     %i.icon-music
        -#     %h4.header.light Music
        -# %li.item
        -#   .box.bg-color.blue
        -#     %i.icon-twitter
        -#     %h4.header.light Twitter
        -# %li.item.wide
        -#   .box.bg-color.red
        -#     %i.icon-shopping-cart
        -#     %h4.header.light Shopping
        -# %li.item.wide
        -#   .box.bg-color.blue
        -#     %i.icon-calendar
        -#     %h4.header.light Calendar
        -# %li.item
        -#   .box.bg-color.blue
        -#     %i.icon-camera
        -#     %h4.header.light Photos
        -# %li.item
        -#   .box.bg-color.purple
        -#     %i.icon-trophy
        -#     %h4.header.light Trophy
        -# %li.item
        -#   .box.bg-color.orange
        -#     %i.icon-food
        -#     %h4.header.light Food

%section
  .container-fluid.gap-bottom
    .row-fluid.aligncenter
      .span3.small-chart.charts
        %span.inlinebar.green
        %h1 -$1,458
        %h4 Startup Cash
      .span3.small-chart.charts
        %span.inlinestackbar.blue
        %h1 +951
        %h4 Geeks vs Nerds
      .span3.small-chart.charts
        %span.inlinepie.red
        %h1 +24
        %h4 Code Type
      .span3.small-chart.charts
        %span.inlineline.green
        %h1 +3,550
        %h4 Click Rate

-# %section.bordered.bg-color.dark-grey
-#   .container-fluid
-#     .row-fluid
-#       .span12
-#         %h3.light.aligncenter Sign Up Rate
-#         #flot-line-filled.graph-area.charts

-# %section.bordered
-#   .container-fluid
-#     .row-fluid
-#       .span12
-#         #myCarousel.carousel.carousel-custom.slide
-#           .carousel-inner
-#             .item.active
-#               %h2.light Consectetur twee american apparel assumenda
-#               %p
-#                 Bushwick est placeat DIY. Kogi magna voluptate, meh do bespoke quis flannel cosby sweater culpa placeat farm-to-table Austin helvetica. Dreamcatcher reprehenderit ugh odio mumblecore. Voluptate fixie master cleanse, adipisicing selfies hoodie before they sold out meh put a bird on it deserunt plaid dolor letterpress velit. Dolore esse dolor, enim banksy nesciunt neutra eiusmod deserunt. Austin selfies nihil blue bottle helvetica. Squid flannel selfies photo booth, locavore art party meh veniam ut irure DIY ethical readymade ullamco sed.
-#             .item
-#               %h2.light Locavore art party meh veniam ut irure
-#               %p
-#                 Bushwick est placeat DIY. Kogi magna voluptate, meh do bespoke quis flannel cosby sweater culpa placeat farm-to-table Austin helvetica. Dreamcatcher reprehenderit ugh odio mumblecore. Voluptate fixie master cleanse, adipisicing selfies hoodie before they sold out meh put a bird on it deserunt plaid dolor letterpress velit. Dolore esse dolor, enim banksy nesciunt neutra eiusmod deserunt. Austin selfies nihil blue bottle helvetica. Squid flannel selfies photo booth, locavore art party meh veniam ut irure DIY ethical readymade ullamco sed.
-#           %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"}
-#             %i.icon-arrow-left
-#           %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"}
-#             %i.icon-arrow-right

%section.bordered
  .container-fluid
    .row-fluid
      .span4
        .widget
          .widget-header
            %i.icon-heart.icon-metro
            %h3 featured articles
          .widget-content
            %ul.unstyled.list-article
              %li
                %header
                  %img.thumbnail{:src => "http://placehold.it/40x40/0072c6/ffffff"}/
                  %h3.light Ethical readymade ullamco sed
              %li
                %header
                  %img.thumbnail{:src => "http://placehold.it/40x40/0072c6/ffffff"}/
                  %h3.light Pickled consectetur brunch elit nisi narwhal
              %li
                %header
                  %img.thumbnail{:src => "http://placehold.it/40x40/0072c6/ffffff"}/
                  %h3.light Adipisicing selfies hoodie before
              %li
                %header
                  %img.thumbnail{:src => "http://placehold.it/40x40/0072c6/ffffff"}/
                  %h3.light Locavore art party meh veniam
      .span4
        .widget
          .widget-header
            %i.icon-user.icon-metro
            %h3 user opinions
          .widget-content
            %ul.unstyled.list-comment
              %li
                %img.thumbnail{:src => "img/styler/user-small.png"}/
                %p Four loko echo park photo booth meh. Keytar quinoa gluten-free dolor terry richardson cred. Minim sriracha put a bird on it veniam
                %strong.name Haraldur Thorleifsson
                %a{:href => "#"} Google.com
              %li
                %img.thumbnail{:src => "img/styler/user-small.png"}/
                %p Minim sriracha put a bird on it veniam, freegan wolf artisan pickled incididunt american apparel nesciunt butcher odio jean shorts DIY
                %strong.name Ilias Sounas
                %a{:href => "#"} Apple.com
      .span4
        .widget.bg-color.dark-grey
          .widget-header
            %i.icon-calendar.icon-metro
            %h3 events
          .widget-content
            Ad artisan accusamus mixtape aliquip, bushwick try-hard deep v scenester biodiesel jean shorts keffiyeh. Bespoke qui master cleanse anim tousled minim. Art party occupy post-ironic messenger bag ut, quinoa mlkshk twee anim banksy lo-fi tonx voluptate.
    %div

app/views/backend/monuments/_form.html.haml
= simple_form_for [:backend, @monument], url: backend_monuments_path, html: { class: 'form-skin' } do |form|
  = form.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
  - form.globalize_fields_for_locale :el do |fields|
    = fields.input :name
    = fields.input :title
    = fields.input :description, input_html: { :class => "ckeditor" }
  = form.button :submit

app/views/backend/monuments/index.html.haml
- model_name = controller_name.classify.pluralize

%header.content-header
  %h1.light.no-margin= model_name.to_s
%section.bordered
  .container-fluid
    .row-fluid
      .span12
        .dataTables_wrapper{ role: 'grid' }
          .actions
            = link_to 'New monument', new_backend_monument_path, class: 'btn-flat btn btn-green btn-small no-radius'

          %table.table.table-striped.table-data.dataTable
            %thead
              %tr{ role: 'row' }
                %th.image{colspan: 1, width: 150}
                %th Name
                %th Title
                %th Creator
                %th.actions{colspan: 2}
            %tbody{:'aria-live' => 'polite', :'aria-relevant' => 'all'}
              %tr          
                %th= ''
                %th Olymompian zeus
                %th Olymompian zeus the god above all
                %th= '20.10.2013'
                %th
                  .actions
                    
                    = link_to '', class: 'span5' do 
                      %i.icon-eye-open
                      Edit
                    
                    = link_to '', class: 'span5' do 
                      %i.icon-remove
                      Delete

                = render @monuments
    
          .dataTables_info Showing 1 to 10 of 57 entries
          .dataTables_paginate.paging_two_button
            %a.paginate_disabled_previous Previous
            %a.paginate_enabled_next Next
            

app/views/backend/monuments/new.html.haml
- model_name = controller_name.classify

%header.content-header
  %h1.light.no-margin= model_name.to_s
%section.bordered
  .container-fluid
    .row-fluid
      .span12
        = render partial: 'form'

app/views/homepage/show.html.haml
%header.content-header
  %h1.light.no-margin Dashboard

%section.bordered
  .container-fluid
    .metro-area
      %ul.metro-shortcut.clearfix.unstyled
        %li.item.wide
          .box.bg-color.green
            %i.icon-camera
            %span.count 10
            %h4.header.light New Messages
        -# %li.item
        -#   .box.bg-color.red
        -#     %i.icon-music
        -#     %h4.header.light Music
        -# %li.item
        -#   .box.bg-color.blue
        -#     %i.icon-twitter
        -#     %h4.header.light Twitter
        -# %li.item.wide
        -#   .box.bg-color.red
        -#     %i.icon-shopping-cart
        -#     %h4.header.light Shopping
        -# %li.item.wide
        -#   .box.bg-color.blue
        -#     %i.icon-calendar
        -#     %h4.header.light Calendar
        -# %li.item
        -#   .box.bg-color.blue
        -#     %i.icon-camera
        -#     %h4.header.light Photos
        -# %li.item
        -#   .box.bg-color.purple
        -#     %i.icon-trophy
        -#     %h4.header.light Trophy
        -# %li.item
        -#   .box.bg-color.orange
        -#     %i.icon-food
        -#     %h4.header.light Food

%section
  .container-fluid.gap-bottom
    .row-fluid.aligncenter
      .span3.small-chart.charts
        %span.inlinebar.green
        %h1 -$1,458
        %h4 Startup Cash
      .span3.small-chart.charts
        %span.inlinestackbar.blue
        %h1 +951
        %h4 Geeks vs Nerds
      .span3.small-chart.charts
        %span.inlinepie.red
        %h1 +24
        %h4 Code Type
      .span3.small-chart.charts
        %span.inlineline.green
        %h1 +3,550
        %h4 Click Rate

-# %section.bordered.bg-color.dark-grey
-#   .container-fluid
-#     .row-fluid
-#       .span12
-#         %h3.light.aligncenter Sign Up Rate
-#         #flot-line-filled.graph-area.charts

-# %section.bordered
-#   .container-fluid
-#     .row-fluid
-#       .span12
-#         #myCarousel.carousel.carousel-custom.slide
-#           .carousel-inner
-#             .item.active
-#               %h2.light Consectetur twee american apparel assumenda
-#               %p
-#                 Bushwick est placeat DIY. Kogi magna voluptate, meh do bespoke quis flannel cosby sweater culpa placeat farm-to-table Austin helvetica. Dreamcatcher reprehenderit ugh odio mumblecore. Voluptate fixie master cleanse, adipisicing selfies hoodie before they sold out meh put a bird on it deserunt plaid dolor letterpress velit. Dolore esse dolor, enim banksy nesciunt neutra eiusmod deserunt. Austin selfies nihil blue bottle helvetica. Squid flannel selfies photo booth, locavore art party meh veniam ut irure DIY ethical readymade ullamco sed.
-#             .item
-#               %h2.light Locavore art party meh veniam ut irure
-#               %p
-#                 Bushwick est placeat DIY. Kogi magna voluptate, meh do bespoke quis flannel cosby sweater culpa placeat farm-to-table Austin helvetica. Dreamcatcher reprehenderit ugh odio mumblecore. Voluptate fixie master cleanse, adipisicing selfies hoodie before they sold out meh put a bird on it deserunt plaid dolor letterpress velit. Dolore esse dolor, enim banksy nesciunt neutra eiusmod deserunt. Austin selfies nihil blue bottle helvetica. Squid flannel selfies photo booth, locavore art party meh veniam ut irure DIY ethical readymade ullamco sed.
-#           %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"}
-#             %i.icon-arrow-left
-#           %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"}
-#             %i.icon-arrow-right

%section.bordered
  .container-fluid
    .row-fluid
      .span4
        .widget
          .widget-header
            %i.icon-heart.icon-metro
            %h3 featured articles
          .widget-content
            %ul.unstyled.list-article
              %li
                %header
                  %img.thumbnail{:src => "http://placehold.it/40x40/0072c6/ffffff"}/
                  %h3.light Ethical readymade ullamco sed
              %li
                %header
                  %img.thumbnail{:src => "http://placehold.it/40x40/0072c6/ffffff"}/
                  %h3.light Pickled consectetur brunch elit nisi narwhal
              %li
                %header
                  %img.thumbnail{:src => "http://placehold.it/40x40/0072c6/ffffff"}/
                  %h3.light Adipisicing selfies hoodie before
              %li
                %header
                  %img.thumbnail{:src => "http://placehold.it/40x40/0072c6/ffffff"}/
                  %h3.light Locavore art party meh veniam
      .span4
        .widget
          .widget-header
            %i.icon-user.icon-metro
            %h3 user opinions
          .widget-content
            %ul.unstyled.list-comment
              %li
                %img.thumbnail{:src => "img/styler/user-small.png"}/
                %p Four loko echo park photo booth meh. Keytar quinoa gluten-free dolor terry richardson cred. Minim sriracha put a bird on it veniam
                %strong.name Haraldur Thorleifsson
                %a{:href => "#"} Google.com
              %li
                %img.thumbnail{:src => "img/styler/user-small.png"}/
                %p Minim sriracha put a bird on it veniam, freegan wolf artisan pickled incididunt american apparel nesciunt butcher odio jean shorts DIY
                %strong.name Ilias Sounas
                %a{:href => "#"} Apple.com
      .span4
        .widget.bg-color.dark-grey
          .widget-header
            %i.icon-calendar.icon-metro
            %h3 events
          .widget-content
            Ad artisan accusamus mixtape aliquip, bushwick try-hard deep v scenester biodiesel jean shorts keffiyeh. Bespoke qui master cleanse anim tousled minim. Art party occupy post-ironic messenger bag ut, quinoa mlkshk twee anim banksy lo-fi tonx voluptate.
    %div

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PathsCc</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "PathsCc"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body

    .container-fluid
      .row-fluid
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Company 2013
    = javascript_include_tag "application"

app/views/layouts/backend.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "PathsCc"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true
    %link{:href => "http://fonts.googleapis.com/css?family=Ubuntu:300,400,500", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Lato:100,300,400,700", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700", :rel => "stylesheet", :type => "text/css"}/

    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body{"cz-shortcut-listen" => "true"}
    %header
      .navbar
        .navbar-inner
          .branding.pull-left
            %h1.light.no-margin.logo
              %span in
              Paths.cc

          %ul.nav.pull-right
            %li.dropdown
              = link_to '#', class: 'dropdown-toggle', :'data-toggle' => 'dropdown' do
                = current_user.username.upcase.to_s
                %b.caret
              %ul.dropdown-menu
                %li= link_to 'Settings', '', class: 'btn btn-flat btn-blue'
                %li= link_to 'Logout', backend_logout_path, class: 'btn btn-flat' if current_user

    %aside.sidebar.sidebar-left.collapse
      %form.sidebar-search
        %input{:placeholder => "Search", :type => "text"}/
      %h3.sidebar-header.light Navigation
      = render_navigation context: :backend, level: 1

    %section.content
      .bordered
        .container-fluid
          .row-fluid
            .span12
              .hero-unit
                = render_navigation context: :backend, renderer: :links, level: 2
    
      = yield

    %aside.sidebar.sidebar-right
      .widget
        %header.widget-header
          %i.icon-user.icon-metro
          %h3.light online users

        - if current_users_list
          %article.widget-content
            %ul.unstyled.user-list.clearfix
              - current_users_list.split(',').each do |logged_user|
                %li
                  = gravatar_image_tag(current_user.email, :alt => current_user.username, :gravatar => { :size => 40 } )

      
      .widget.bg-color.grey
        %header.widget-header
          %i.icon-plus-sign.icon-metro
          %h3 latest 
        %article.widget-content
          %ul.unstyled.list
            %li
              %i.icon-folder-close
              %span.font-bold Metroboard
              %span.pull-right.label.label-success completed
            %li
              %i.icon-folder-close
              %span.font-bold Boardskin
              %span.pull-right.label.label-important 7 tasks
            %li
              %i.icon-folder-close
              %span.font-bold Landingskin
              %span.pull-right.label.label-important 1 task
            %li
              %i.icon-folder-close
              %span.font-bold Plain
              %span.pull-right.label.label-important 3 tasks
            %li
              %i.icon-folder-close
              %span.font-bold Website
              %span.pull-right.label.label-warning Pending
            %li
              %i.icon-folder-close
              %span.font-bold Snippets
              %span.pull-right.label.label-warning 4 tasks
            %li
              %i.icon-folder-close
              %span.font-bold Styler
              %span.pull-right.label.label-default unknown

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/layouts/sessions.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "PathsCc"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body
    .container
      .row
        .span4.offset4.well
          %legend Please Sign In
          = bootstrap_flash
          = yield

    = javascript_include_tag "application"